import type { Metadata } from 'next';
import './globals.css';
import { LayoutProps } from '@/lib/types/common';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }: LayoutProps) {
  return children;
}
